// AUTO-GENERATED by scripts/printful-sync.ts — do not edit manually
// Generated on: 2025-09-07T12:23:03.190Z
// Total variants: 8

export type CapVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price?: string;
  name: string;
  externalId?: string;
  sku?: string;
};

export const CapVariants: CapVariant[] = [
  {
    key: "68a9f52cc3d834",
    catalogVariantId: 7854,
    syncVariantId: 4938937571,
    price: "19.99",
    name: "Variant 4938937571",
    externalId: "68a9f52cc3d834",
    sku: "68a9f52cc3d834",
  },
  {
    key: "68a9f52cc3d899",
    catalogVariantId: 7857,
    syncVariantId: 4938937572,
    price: "19.99",
    name: "Variant 4938937572",
    externalId: "68a9f52cc3d899",
    sku: "68a9f52cc3d899",
  },
  {
    key: "68a9f52cc3d8f7",
    catalogVariantId: 12736,
    syncVariantId: 4938937573,
    price: "19.99",
    name: "Variant 4938937573",
    externalId: "68a9f52cc3d8f7",
    sku: "68a9f52cc3d8f7",
  },
  {
    key: "68a9f52cc3d939",
    catalogVariantId: 7855,
    syncVariantId: 4938937574,
    price: "19.99",
    name: "Variant 4938937574",
    externalId: "68a9f52cc3d939",
    sku: "68a9f52cc3d939",
  },
  {
    key: "68a9f52cc3d988",
    catalogVariantId: 7859,
    syncVariantId: 4938937575,
    price: "19.99",
    name: "Variant 4938937575",
    externalId: "68a9f52cc3d988",
    sku: "68a9f52cc3d988",
  },
  {
    key: "68a9f52cc3d9d7",
    catalogVariantId: 7858,
    syncVariantId: 4938937576,
    price: "19.99",
    name: "Variant 4938937576",
    externalId: "68a9f52cc3d9d7",
    sku: "68a9f52cc3d9d7",
  },
  {
    key: "68a9f52cc3da28",
    catalogVariantId: 7856,
    syncVariantId: 4938937577,
    price: "19.99",
    name: "Variant 4938937577",
    externalId: "68a9f52cc3da28",
    sku: "68a9f52cc3da28",
  },
  {
    key: "68a9f52cc3da68",
    catalogVariantId: 7853,
    syncVariantId: 4938937578,
    price: "19.99",
    name: "Variant 4938937578",
    externalId: "68a9f52cc3da68",
    sku: "68a9f52cc3da68",
  },
];

// Helper function to find variant by key
export function findCapVariant(key: string): CapVariant | undefined {
  return CapVariants.find(v => v.key === key);
}

// Helper function to find variant by catalog variant ID
export function findCapVariantByCatalogId(catalogVariantId: number): CapVariant | undefined {
  return CapVariants.find(v => v.catalogVariantId === catalogVariantId);
}