// AUTO-GENERATED by scripts/printful-sync.ts — do not edit manually
// Generated on: 2025-08-26T14:38:57.274Z
// Total variants: 8

export type CapVariant = {
  key: string;
  catalogVariantId: number;      // Printful catalog variant ID (reference)
  syncVariantId: number;         // Printful sync variant ID (reference)
  price?: string;
  name: string;
  color: string;
  colorHex: string;
  externalId?: string;           // Primary Printful variant ID for ordering
  sku?: string;
};

export const CapVariants: CapVariant[] = [
  {
    key: "Black",
    catalogVariantId: 7854,
    syncVariantId: 4938937571,
    price: "19.99",
    name: "Reform UK Cap - Black",
    color: "Black",
    colorHex: "#181717",
    externalId: "68a9f52cc3d834",  // Primary ID for ordering
    sku: "68a9f52cc3d834",
  },
  {
    key: "Navy",
    catalogVariantId: 7857,
    syncVariantId: 4938937572,
    price: "19.99",
    name: "Reform UK Cap - Navy",
    color: "Navy",
    colorHex: "#182031",
    externalId: "68a9f52cc3d899",  // Primary ID for ordering
    sku: "68a9f52cc3d899",
  },
  {
    key: "Dark Grey",
    catalogVariantId: 12736,
    syncVariantId: 4938937573,
    price: "19.99",
    name: "Reform UK Cap - Dark Grey",
    color: "Dark Grey",
    colorHex: "#39353a",
    externalId: "68a9f52cc3d8f7",  // Primary ID for ordering
    sku: "68a9f52cc3d8f7",
  },
  {
    key: "Khaki",
    catalogVariantId: 7855,
    syncVariantId: 4938937574,
    price: "19.99",
    name: "Reform UK Cap - Khaki",
    color: "Khaki",
    colorHex: "#b49771",
    externalId: "68a9f52cc3d939",  // Primary ID for ordering
    sku: "68a9f52cc3d939",
  },
  {
    key: "Stone",
    catalogVariantId: 7859,
    syncVariantId: 4938937575,
    price: "19.99",
    name: "Reform UK Cap - Stone",
    color: "Stone",
    colorHex: "#d6bdad",
    externalId: "68a9f52cc3d988",  // Primary ID for ordering
    sku: "68a9f52cc3d988",
  },
  {
    key: "Pink",
    catalogVariantId: 7858,
    syncVariantId: 4938937576,
    price: "19.99",
    name: "Reform UK Cap - Pink",
    color: "Pink",
    colorHex: "#fab2ba",
    externalId: "68a9f52cc3d9d7",  // Primary ID for ordering
    sku: "68a9f52cc3d9d7",
  },
  {
    key: "Light Blue",
    catalogVariantId: 7856,
    syncVariantId: 4938937577,
    price: "19.99",
    name: "Reform UK Cap - Light Blue",
    color: "Light Blue",
    colorHex: "#b5cbda",
    externalId: "68a9f52cc3da28",  // Primary ID for ordering
    sku: "68a9f52cc3da28",
  },
  {
    key: "White",
    catalogVariantId: 7853,
    syncVariantId: 4938937578,
    price: "19.99",
    name: "Reform UK Cap - White",
    color: "White",
    colorHex: "#ffffff",
    externalId: "68a9f52cc3da68",  // Primary ID for ordering
    sku: "68a9f52cc3da68",
  },
];

// Helper function to find variant by key
export function findCapVariant(key: string): CapVariant | undefined {
  return CapVariants.find(v => v.key === key);
}

// Helper function to find variant by catalog variant ID
export function findCapVariantByCatalogId(catalogVariantId: number): CapVariant | undefined {
  return CapVariants.find(v => v.catalogVariantId === catalogVariantId);
}

// Helper function to find variant by color name
export function findCapVariantByColor(color: string): CapVariant | undefined {
  return CapVariants.find(v => v.color === color);
}

// Helper function to find variant by external ID (Primary Printful variant ID for ordering)
export function findCapVariantByExternalId(externalId: string): CapVariant | undefined {
  return CapVariants.find(v => v.externalId === externalId);
}

// Export cap colors array for easy access
export const capColors = [
  { name: 'Black', hex: '#181717' },
  { name: 'Navy', hex: '#182031' },
  { name: 'Dark Grey', hex: '#39353a' },
  { name: 'Khaki', hex: '#b49771' },
  { name: 'Stone', hex: '#d6bdad' },
  { name: 'Pink', hex: '#fab2ba' },
  { name: 'Light Blue', hex: '#b5cbda' },
  { name: 'White', hex: '#ffffff', border: true }
];