// AUTO-GENERATED by scripts/printful-sync.ts — do not edit manually
// Generated on: 2025-08-26T14:38:57.277Z
// Total variants: 1

export type MousepadVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price?: string;
  name: string;
  externalId?: string;
  sku?: string;
};

export const MousepadVariants: MousepadVariant[] = [
  {
    key: "68a9f6e8eeb689",
    catalogVariantId: 13097,
    syncVariantId: 4938942751,
    price: "14.99",
    name: "Variant 4938942751",
    externalId: "68a9f6e8eeb689",
    sku: "68a9f6e8eeb689",
  },
];

// Helper function to find variant by key
export function findMousepadVariant(key: string): MousepadVariant | undefined {
  return MousepadVariants.find(v => v.key === key);
}

// Helper function to find variant by catalog variant ID
export function findMousepadVariantByCatalogId(catalogVariantId: number): MousepadVariant | undefined {
  return MousepadVariants.find(v => v.catalogVariantId === catalogVariantId);
}