// AUTO-GENERATED by scripts/printful-sync.ts — do not edit manually
// Generated on: 2025-09-07T12:23:03.192Z
// Total variants: 1

export type TotebagVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price?: string;
  name: string;
  externalId?: string;
  sku?: string;
};

export const TotebagVariants: TotebagVariant[] = [
  {
    key: "68a8a3b526d2f1",
    catalogVariantId: 10457,
    syncVariantId: 4937855201,
    price: "24.99",
    name: "Variant 4937855201",
    externalId: "68a8a3b526d2f1",
    sku: "68a8a3b526d2f1",
  },
];

// Helper function to find variant by key
export function findTotebagVariant(key: string): TotebagVariant | undefined {
  return TotebagVariants.find(v => v.key === key);
}

// Helper function to find variant by catalog variant ID
export function findTotebagVariantByCatalogId(catalogVariantId: number): TotebagVariant | undefined {
  return TotebagVariants.find(v => v.catalogVariantId === catalogVariantId);
}