// AUTO-GENERATED by scripts/fix-tshirt-overlapping-colors.ts — FIXED VERSION
// Fixed overlapping colors: Each color appears in exactly one design
// Generated on: 2025-08-26T20:49:38.497Z
// Total variants: 60 (20 DARK + 40 LIGHT)
// Each color is assigned to exactly one design (DARK or LIGHT)

export type TshirtVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price: string;
  design: 'DARK' | 'LIGHT';
  size: 'S' | 'M' | 'L' | 'XL' | '2XL';
  color: string;
  colorHex: string;
  externalId: string;
  sku: string;
};

export const TshirtVariants: TshirtVariant[] = [
  {
    key: "68a9d8c287b9e7",
    catalogVariantId: 10376,
    syncVariantId: 4938814128,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287b9e7",
    sku: "68a9d8c287b9e7"
  },
  {
    key: "68a9d8c287ba54",
    catalogVariantId: 10377,
    syncVariantId: 4938814129,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287ba54",
    sku: "68a9d8c287ba54"
  },
  {
    key: "68a9d8c287bab6",
    catalogVariantId: 10378,
    syncVariantId: 4938814130,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Light Grey",
    colorHex: "#E5E5E5",
    externalId: "68a9d8c287bab6",
    sku: "68a9d8c287bab6"
  },
  {
    key: "68a9d8c287bb05",
    catalogVariantId: 10379,
    syncVariantId: 4938814131,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287bb05",
    sku: "68a9d8c287bb05"
  },
  {
    key: "68a9d8c287bb52",
    catalogVariantId: 10380,
    syncVariantId: 4938814132,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287bb52",
    sku: "68a9d8c287bb52"
  },
  {
    key: "68a9d8c287bba4",
    catalogVariantId: 9367,
    syncVariantId: 4938814133,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Ash Grey",
    colorHex: "#B0B0B0",
    externalId: "68a9d8c287bba4",
    sku: "68a9d8c287bba4"
  },
  {
    key: "68a9d8c287bbe7",
    catalogVariantId: 9368,
    syncVariantId: 4938814134,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287bbe7",
    sku: "68a9d8c287bbe7"
  },
  {
    key: "68a9d8c287bc39",
    catalogVariantId: 9369,
    syncVariantId: 4938814135,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Pink",
    colorHex: "#FDbfC7",
    externalId: "68a9d8c287bc39",
    sku: "68a9d8c287bc39"
  },
  {
    key: "68a9daac4dc438",
    catalogVariantId: 4019,
    syncVariantId: 4938821290,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Yellow",
    colorHex: "#FFD667",
    externalId: "68a9daac4dc438",
    sku: "68a9daac4dc438"
  },
  {
    key: "68a9daac4dc482",
    catalogVariantId: 4020,
    syncVariantId: 4938821291,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Mustard",
    colorHex: "#EDA027",
    externalId: "68a9daac4dc482",
    sku: "68a9daac4dc482"
  },
  {
    key: "68a9daac4dc4c4",
    catalogVariantId: 4111,
    syncVariantId: 4938821292,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Orange",
    colorHex: "#FF8C00",
    externalId: "68a9daac4dc4c4",
    sku: "68a9daac4dc4c4"
  },
  {
    key: "68a9daac4dc511",
    catalogVariantId: 4112,
    syncVariantId: 4938821293,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Red",
    colorHex: "#B31217",
    externalId: "68a9daac4dc511",
    sku: "68a9daac4dc511"
  },
  {
    key: "68a9d8c287bc83",
    catalogVariantId: 9370,
    syncVariantId: 4938814136,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287bc83",
    sku: "68a9d8c287bc83"
  },
  {
    key: "68a9d8c287bcd5",
    catalogVariantId: 9371,
    syncVariantId: 4938814137,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287bcd5",
    sku: "68a9d8c287bcd5"
  },
  {
    key: "68a9d8c287bd24",
    catalogVariantId: 4136,
    syncVariantId: 4938814138,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Light Grey",
    colorHex: "#E5E5E5",
    externalId: "68a9d8c287bd24",
    sku: "68a9d8c287bd24"
  },
  {
    key: "68a9d8c287bd79",
    catalogVariantId: 4137,
    syncVariantId: 4938814139,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287bd79",
    sku: "68a9d8c287bd79"
  },
  {
    key: "68a9d8c287bdc6",
    catalogVariantId: 4138,
    syncVariantId: 4938814140,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287bdc6",
    sku: "68a9d8c287bdc6"
  },
  {
    key: "68a9d8c287be03",
    catalogVariantId: 4139,
    syncVariantId: 4938814141,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Ash Grey",
    colorHex: "#B0B0B0",
    externalId: "68a9d8c287be03",
    sku: "68a9d8c287be03"
  },
  {
    key: "68a9d8c287be52",
    catalogVariantId: 4140,
    syncVariantId: 4938814142,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287be52",
    sku: "68a9d8c287be52"
  },
  {
    key: "68a9d8c287bea5",
    catalogVariantId: 6948,
    syncVariantId: 4938814143,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Pink",
    colorHex: "#FDbfC7",
    externalId: "68a9d8c287bea5",
    sku: "68a9d8c287bea5"
  },
  {
    key: "68a9daac4dc7d6",
    catalogVariantId: 8460,
    syncVariantId: 4938821302,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Yellow",
    colorHex: "#FFD667",
    externalId: "68a9daac4dc7d6",
    sku: "68a9daac4dc7d6"
  },
  {
    key: "68a9daac4dc864",
    catalogVariantId: 8461,
    syncVariantId: 4938821303,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Mustard",
    colorHex: "#EDA027",
    externalId: "68a9daac4dc864",
    sku: "68a9daac4dc864"
  },
  {
    key: "68a9daac4dc8b2",
    catalogVariantId: 8462,
    syncVariantId: 4938821304,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Orange",
    colorHex: "#FF8C00",
    externalId: "68a9daac4dc8b2",
    sku: "68a9daac4dc8b2"
  },
  {
    key: "68a9daac4dc904",
    catalogVariantId: 8463,
    syncVariantId: 4938821305,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Red",
    colorHex: "#B31217",
    externalId: "68a9daac4dc904",
    sku: "68a9daac4dc904"
  },
  {
    key: "68a9d8c287bee3",
    catalogVariantId: 6949,
    syncVariantId: 4938814144,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287bee3",
    sku: "68a9d8c287bee3"
  },
  {
    key: "68a9d8c287bf32",
    catalogVariantId: 6950,
    syncVariantId: 4938814145,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287bf32",
    sku: "68a9d8c287bf32"
  },
  {
    key: "68a9d8c287bf85",
    catalogVariantId: 6951,
    syncVariantId: 4938814146,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Light Grey",
    colorHex: "#E5E5E5",
    externalId: "68a9d8c287bf85",
    sku: "68a9d8c287bf85"
  },
  {
    key: "68a9d8c287bfc6",
    catalogVariantId: 6952,
    syncVariantId: 4938814147,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287bfc6",
    sku: "68a9d8c287bfc6"
  },
  {
    key: "68a9d8c287c017",
    catalogVariantId: 4181,
    syncVariantId: 4938814148,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287c017",
    sku: "68a9d8c287c017"
  },
  {
    key: "68a9d8c287c063",
    catalogVariantId: 4182,
    syncVariantId: 4938814149,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Ash Grey",
    colorHex: "#B0B0B0",
    externalId: "68a9d8c287c063",
    sku: "68a9d8c287c063"
  },
  {
    key: "68a9d8c287c0b3",
    catalogVariantId: 4183,
    syncVariantId: 4938814150,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287c0b3",
    sku: "68a9d8c287c0b3"
  },
  {
    key: "68a9d8c287c0f2",
    catalogVariantId: 4184,
    syncVariantId: 4938814151,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Pink",
    colorHex: "#FDbfC7",
    externalId: "68a9d8c287c0f2",
    sku: "68a9d8c287c0f2"
  },
  {
    key: "68a9daac4dcbc1",
    catalogVariantId: 8442,
    syncVariantId: 4938821314,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Yellow",
    colorHex: "#FFD667",
    externalId: "68a9daac4dcbc1",
    sku: "68a9daac4dcbc1"
  },
  {
    key: "68a9daac4dcc04",
    catalogVariantId: 8443,
    syncVariantId: 4938821315,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Mustard",
    colorHex: "#EDA027",
    externalId: "68a9daac4dcc04",
    sku: "68a9daac4dcc04"
  },
  {
    key: "68a9daac4dcc52",
    catalogVariantId: 8444,
    syncVariantId: 4938821316,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Orange",
    colorHex: "#FF8C00",
    externalId: "68a9daac4dcc52",
    sku: "68a9daac4dcc52"
  },
  {
    key: "68a9daac4dccb2",
    catalogVariantId: 4121,
    syncVariantId: 4938821317,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Red",
    colorHex: "#B31217",
    externalId: "68a9daac4dccb2",
    sku: "68a9daac4dccb2"
  },
  {
    key: "68a9d8c287c149",
    catalogVariantId: 4185,
    syncVariantId: 4938814152,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287c149",
    sku: "68a9d8c287c149"
  },
  {
    key: "68a9d8c287c195",
    catalogVariantId: 10360,
    syncVariantId: 4938814153,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287c195",
    sku: "68a9d8c287c195"
  },
  {
    key: "68a9d8c287c1e1",
    catalogVariantId: 10361,
    syncVariantId: 4938814154,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Light Grey",
    colorHex: "#E5E5E5",
    externalId: "68a9d8c287c1e1",
    sku: "68a9d8c287c1e1"
  },
  {
    key: "68a9d8c287c226",
    catalogVariantId: 10362,
    syncVariantId: 4938814155,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287c226",
    sku: "68a9d8c287c226"
  },
  {
    key: "68a9d8c287c272",
    catalogVariantId: 10363,
    syncVariantId: 4938814156,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287c272",
    sku: "68a9d8c287c272"
  },
  {
    key: "68a9d8c287c2c5",
    catalogVariantId: 10364,
    syncVariantId: 4938814157,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Ash Grey",
    colorHex: "#B0B0B0",
    externalId: "68a9d8c287c2c5",
    sku: "68a9d8c287c2c5"
  },
  {
    key: "68a9d8c287c311",
    catalogVariantId: 4026,
    syncVariantId: 4938814158,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287c311",
    sku: "68a9d8c287c311"
  },
  {
    key: "68a9d8c287c367",
    catalogVariantId: 4027,
    syncVariantId: 4938814159,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Pink",
    colorHex: "#FDbfC7",
    externalId: "68a9d8c287c367",
    sku: "68a9d8c287c367"
  },
  {
    key: "68a9daac4dcf77",
    catalogVariantId: 10388,
    syncVariantId: 4938821326,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Yellow",
    colorHex: "#FFD667",
    externalId: "68a9daac4dcf77",
    sku: "68a9daac4dcf77"
  },
  {
    key: "68a9daac4dcfd5",
    catalogVariantId: 8481,
    syncVariantId: 4938821327,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Mustard",
    colorHex: "#EDA027",
    externalId: "68a9daac4dcfd5",
    sku: "68a9daac4dcfd5"
  },
  {
    key: "68a9daac4dd018",
    catalogVariantId: 8482,
    syncVariantId: 4938821328,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Orange",
    colorHex: "#FF8C00",
    externalId: "68a9daac4dd018",
    sku: "68a9daac4dd018"
  },
  {
    key: "68a9daac4dd068",
    catalogVariantId: 8483,
    syncVariantId: 4938821329,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Red",
    colorHex: "#B31217",
    externalId: "68a9daac4dd068",
    sku: "68a9daac4dd068"
  },
  {
    key: "68a9d8c287c3b2",
    catalogVariantId: 4028,
    syncVariantId: 4938814160,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287c3b2",
    sku: "68a9d8c287c3b2"
  },
  {
    key: "68a9d8c287c409",
    catalogVariantId: 4029,
    syncVariantId: 4938814161,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287c409",
    sku: "68a9d8c287c409"
  },
  {
    key: "68a9d8c287c443",
    catalogVariantId: 4030,
    syncVariantId: 4938814162,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Light Grey",
    colorHex: "#E5E5E5",
    externalId: "68a9d8c287c443",
    sku: "68a9d8c287c443"
  },
  {
    key: "68a9d8c287c495",
    catalogVariantId: 4011,
    syncVariantId: 4938814163,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287c495",
    sku: "68a9d8c287c495"
  },
  {
    key: "68a9d8c287c4e9",
    catalogVariantId: 4012,
    syncVariantId: 4938814164,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287c4e9",
    sku: "68a9d8c287c4e9"
  },
  {
    key: "68a9d8c287c535",
    catalogVariantId: 4013,
    syncVariantId: 4938814165,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Ash Grey",
    colorHex: "#B0B0B0",
    externalId: "68a9d8c287c535",
    sku: "68a9d8c287c535"
  },
  {
    key: "68a9d8c287c584",
    catalogVariantId: 4014,
    syncVariantId: 4938814166,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287c584",
    sku: "68a9d8c287c584"
  },
  {
    key: "68a9d8c287c5d4",
    catalogVariantId: 4015,
    syncVariantId: 4938814167,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Pink",
    colorHex: "#FDbfC7",
    externalId: "68a9d8c287c5d4",
    sku: "68a9d8c287c5d4"
  },
  {
    key: "68a9daac4dd321",
    catalogVariantId: 4162,
    syncVariantId: 4938821338,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Yellow",
    colorHex: "#FFD667",
    externalId: "68a9daac4dd321",
    sku: "68a9daac4dd321"
  },
  {
    key: "68a9daac4dd376",
    catalogVariantId: 4163,
    syncVariantId: 4938821339,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Mustard",
    colorHex: "#EDA027",
    externalId: "68a9daac4dd376",
    sku: "68a9daac4dd376"
  },
  {
    key: "68a9daac4dd3c2",
    catalogVariantId: 4164,
    syncVariantId: 4938821340,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Orange",
    colorHex: "#FF8C00",
    externalId: "68a9daac4dd3c2",
    sku: "68a9daac4dd3c2"
  },
  {
    key: "68a9daac4dd416",
    catalogVariantId: 4165,
    syncVariantId: 4938821341,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Red",
    colorHex: "#B31217",
    externalId: "68a9daac4dd416",
    sku: "68a9daac4dd416"
  }
];

// Helper Functions
export function findTshirtVariant(design: 'DARK' | 'LIGHT', size: string, color: string): TshirtVariant | undefined {
  return TshirtVariants.find(variant => 
    variant.design === design && 
    variant.size === size && 
    variant.color === color
  );
}

export function findTshirtVariantByCatalogId(catalogId: number): TshirtVariant | undefined {
  return TshirtVariants.find(variant => variant.catalogVariantId === catalogId);
}

export function findTshirtVariantByExternalId(externalId: string): TshirtVariant | undefined {
  return TshirtVariants.find(variant => variant.externalId === externalId);
}

export function getTshirtVariantsByDesign(design: 'DARK' | 'LIGHT'): TshirtVariant[] {
  return TshirtVariants.filter(variant => variant.design === design);
}

export function getTshirtVariantsBySize(size: string): TshirtVariant[] {
  return TshirtVariants.filter(variant => variant.size === size);
}

export function getTshirtVariantsByColor(color: string): TshirtVariant[] {
  return TshirtVariants.filter(variant => variant.color === color);
}

// Get unique designs, sizes, and colors
export const tshirtDesigns = ['DARK', 'LIGHT'] as const;
export const tshirtSizes = ['S', 'M', 'L', 'XL', '2XL'] as const;

// Define the actual t-shirt colors with hex codes (arranged light to dark)
export const tshirtColors = [
  { name: 'White', hex: '#FFFFFF', border: true },
  { name: 'Ash', hex: '#F0F1EA' },
  { name: 'Light Grey', hex: '#E5E5E5', border: true },
  { name: 'Heather Dust', hex: '#E5D9C9' },
  { name: 'Athletic Heather', hex: '#CECECC' },
  { name: 'Ash Grey', hex: '#B0B0B0' },
  { name: 'Heather Prism Peach', hex: '#F3C2B2' },
  { name: 'Pink', hex: '#FDbfC7' },
  { name: 'Yellow', hex: '#FFD667' },
  { name: 'Mustard', hex: '#EDA027' },
  { name: 'Orange', hex: '#FF8C00' },
  { name: 'Red', hex: '#B31217' },
  { name: 'Burgundy', hex: '#800020' },
  { name: 'Mauve', hex: '#BF6E6E' },
  { name: 'Steel Blue', hex: '#668EA7' },
  { name: 'Heather Deep Teal', hex: '#447085' },
  { name: 'Forest Green', hex: '#2D5016' },
  { name: 'Navy', hex: '#1B365D' },
  { name: 'Charcoal', hex: '#333333' },
  { name: 'Black', hex: '#000000' }
];

// Color design mapping for reference
export const colorDesignMapping: { [key: string]: 'DARK' | 'LIGHT' } = {
  "Black": "DARK",
  "Navy": "DARK",
  "Charcoal": "DARK",
  "Forest Green": "DARK",
  "Burgundy": "DARK",
  "Red": "DARK",
  "Orange": "DARK",
  "Mustard": "DARK",
  "Yellow": "DARK",
  "Steel Blue": "DARK",
  "Heather Deep Teal": "DARK",
  "Mauve": "DARK",
  "White": "LIGHT",
  "Ash": "LIGHT",
  "Light Grey": "LIGHT",
  "Heather Dust": "LIGHT",
  "Athletic Heather": "LIGHT",
  "Ash Grey": "LIGHT",
  "Heather Prism Peach": "LIGHT",
  "Pink": "LIGHT"
};

// IMPORTANT: This ensures each color appears in exactly one design
// No more overlapping colors between DARK and LIGHT designs
// Customer selects color + size, system auto-routes to correct Printful product
