// AUTO-GENERATED by scripts/create-complete-tshirt-variants.ts — PRODUCTION READY
// Complete T-Shirt Variants with Correct Printful IDs
// Generated on: 2025-08-26T21:07:34.002Z
// Total variants: 100 (60 DARK + 40 LIGHT)
// Each color appears in exactly one design - NO OVERLAPPING COLORS
// Guaranteed correct Printful routing for all orders

export type TshirtVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price: string;
  design: 'DARK' | 'LIGHT';
  size: 'S' | 'M' | 'L' | 'XL' | '2XL';
  color: string;
  colorHex: string;
  externalId: string;
  sku: string;
};

export const TshirtVariants: TshirtVariant[] = [
  {
    key: "DARK-Army-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Army",
    colorHex: "#4B5320",
    externalId: "68a9daac4dcb25",
    sku: "DARK-Army-S"
  },
  {
    key: "DARK-Army-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Army",
    colorHex: "#4B5320",
    externalId: "68a9daac4dcb79",
    sku: "DARK-Army-M"
  },
  {
    key: "DARK-Army-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Army",
    colorHex: "#4B5320",
    externalId: "68a9daac4dcbc1",
    sku: "DARK-Army-L"
  },
  {
    key: "DARK-Army-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Army",
    colorHex: "#4B5320",
    externalId: "68a9daac4dcc04",
    sku: "DARK-Army-XL"
  },
  {
    key: "DARK-Army-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Army",
    colorHex: "#4B5320",
    externalId: "68a9daac4dcc52",
    sku: "DARK-Army-2XL"
  },
  {
    key: "DARK-Asphalt-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Asphalt",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dc997",
    sku: "DARK-Asphalt-S"
  },
  {
    key: "DARK-Asphalt-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Asphalt",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dc9e2",
    sku: "DARK-Asphalt-M"
  },
  {
    key: "DARK-Asphalt-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Asphalt",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dca33",
    sku: "DARK-Asphalt-L"
  },
  {
    key: "DARK-Asphalt-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Asphalt",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dca85",
    sku: "DARK-Asphalt-XL"
  },
  {
    key: "DARK-Asphalt-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Asphalt",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dcad1",
    sku: "DARK-Asphalt-2XL"
  },
  {
    key: "DARK-Autumn-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Autumn",
    colorHex: "#8B4513",
    externalId: "68a9daac4dce36",
    sku: "DARK-Autumn-S"
  },
  {
    key: "DARK-Autumn-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Autumn",
    colorHex: "#8B4513",
    externalId: "68a9daac4dce81",
    sku: "DARK-Autumn-M"
  },
  {
    key: "DARK-Autumn-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Autumn",
    colorHex: "#8B4513",
    externalId: "68a9daac4dcee9",
    sku: "DARK-Autumn-L"
  },
  {
    key: "DARK-Autumn-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Autumn",
    colorHex: "#8B4513",
    externalId: "68a9daac4dcf23",
    sku: "DARK-Autumn-XL"
  },
  {
    key: "DARK-Autumn-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Autumn",
    colorHex: "#8B4513",
    externalId: "68a9daac4dcf77",
    sku: "DARK-Autumn-2XL"
  },
  {
    key: "DARK-Black-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Black",
    colorHex: "#000000",
    externalId: "68a9daac4dc349",
    sku: "DARK-Black-S"
  },
  {
    key: "DARK-Black-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Black",
    colorHex: "#000000",
    externalId: "68a9daac4dc395",
    sku: "DARK-Black-M"
  },
  {
    key: "DARK-Black-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Black",
    colorHex: "#000000",
    externalId: "68a9daac4dc3e8",
    sku: "DARK-Black-L"
  },
  {
    key: "DARK-Black-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Black",
    colorHex: "#000000",
    externalId: "68a9daac4dc438",
    sku: "DARK-Black-XL"
  },
  {
    key: "DARK-Black-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Black",
    colorHex: "#000000",
    externalId: "68a9daac4dc482",
    sku: "DARK-Black-2XL"
  },
  {
    key: "DARK-Black Heather-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Black Heather",
    colorHex: "#1C1C1C",
    externalId: "68a9daac4dc184",
    sku: "DARK-Black Heather-S"
  },
  {
    key: "DARK-Black Heather-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Black Heather",
    colorHex: "#1C1C1C",
    externalId: "68a9daac4dc201",
    sku: "DARK-Black Heather-M"
  },
  {
    key: "DARK-Black Heather-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Black Heather",
    colorHex: "#1C1C1C",
    externalId: "68a9daac4dc263",
    sku: "DARK-Black Heather-L"
  },
  {
    key: "DARK-Black Heather-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Black Heather",
    colorHex: "#1C1C1C",
    externalId: "68a9daac4dc2a4",
    sku: "DARK-Black Heather-XL"
  },
  {
    key: "DARK-Black Heather-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Black Heather",
    colorHex: "#1C1C1C",
    externalId: "68a9daac4dc2f9",
    sku: "DARK-Black Heather-2XL"
  },
  {
    key: "DARK-Dark Grey Heather-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Dark Grey Heather",
    colorHex: "#696969",
    externalId: "68a9daac4dc7d6",
    sku: "DARK-Dark Grey Heather-S"
  },
  {
    key: "DARK-Dark Grey Heather-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Dark Grey Heather",
    colorHex: "#696969",
    externalId: "68a9daac4dc864",
    sku: "DARK-Dark Grey Heather-M"
  },
  {
    key: "DARK-Dark Grey Heather-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Dark Grey Heather",
    colorHex: "#696969",
    externalId: "68a9daac4dc8b2",
    sku: "DARK-Dark Grey Heather-L"
  },
  {
    key: "DARK-Dark Grey Heather-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Dark Grey Heather",
    colorHex: "#696969",
    externalId: "68a9daac4dc904",
    sku: "DARK-Dark Grey Heather-XL"
  },
  {
    key: "DARK-Dark Grey Heather-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Dark Grey Heather",
    colorHex: "#696969",
    externalId: "68a9daac4dc952",
    sku: "DARK-Dark Grey Heather-2XL"
  },
  {
    key: "DARK-Heather Deep Teal-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Heather Deep Teal",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dcfd5",
    sku: "DARK-Heather Deep Teal-S"
  },
  {
    key: "DARK-Heather Deep Teal-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Heather Deep Teal",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dd018",
    sku: "DARK-Heather Deep Teal-M"
  },
  {
    key: "DARK-Heather Deep Teal-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Heather Deep Teal",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dd068",
    sku: "DARK-Heather Deep Teal-L"
  },
  {
    key: "DARK-Heather Deep Teal-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Heather Deep Teal",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dd0b3",
    sku: "DARK-Heather Deep Teal-XL"
  },
  {
    key: "DARK-Heather Deep Teal-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Heather Deep Teal",
    colorHex: "#2F4F4F",
    externalId: "68a9daac4dd102",
    sku: "DARK-Heather Deep Teal-2XL"
  },
  {
    key: "DARK-Mauve-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Mauve",
    colorHex: "#E0B0FF",
    externalId: "68a9daac4dd149",
    sku: "DARK-Mauve-S"
  },
  {
    key: "DARK-Mauve-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Mauve",
    colorHex: "#E0B0FF",
    externalId: "68a9daac4dd197",
    sku: "DARK-Mauve-M"
  },
  {
    key: "DARK-Mauve-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Mauve",
    colorHex: "#E0B0FF",
    externalId: "68a9daac4dd1e9",
    sku: "DARK-Mauve-L"
  },
  {
    key: "DARK-Mauve-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Mauve",
    colorHex: "#E0B0FF",
    externalId: "68a9daac4dd236",
    sku: "DARK-Mauve-XL"
  },
  {
    key: "DARK-Mauve-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Mauve",
    colorHex: "#E0B0FF",
    externalId: "68a9daac4dd283",
    sku: "DARK-Mauve-2XL"
  },
  {
    key: "DARK-Navy-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Navy",
    colorHex: "#000080",
    externalId: "68a9daac4dc4c4",
    sku: "DARK-Navy-S"
  },
  {
    key: "DARK-Navy-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Navy",
    colorHex: "#000080",
    externalId: "68a9daac4dc511",
    sku: "DARK-Navy-M"
  },
  {
    key: "DARK-Navy-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Navy",
    colorHex: "#000080",
    externalId: "68a9daac4dc564",
    sku: "DARK-Navy-L"
  },
  {
    key: "DARK-Navy-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Navy",
    colorHex: "#000080",
    externalId: "68a9daac4dc5b7",
    sku: "DARK-Navy-XL"
  },
  {
    key: "DARK-Navy-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Navy",
    colorHex: "#000080",
    externalId: "68a9daac4dc603",
    sku: "DARK-Navy-2XL"
  },
  {
    key: "DARK-Olive-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Olive",
    colorHex: "#808000",
    externalId: "68a9daac4dccb2",
    sku: "DARK-Olive-S"
  },
  {
    key: "DARK-Olive-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Olive",
    colorHex: "#808000",
    externalId: "68a9daac4dccf5",
    sku: "DARK-Olive-M"
  },
  {
    key: "DARK-Olive-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Olive",
    colorHex: "#808000",
    externalId: "68a9daac4dcd47",
    sku: "DARK-Olive-L"
  },
  {
    key: "DARK-Olive-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Olive",
    colorHex: "#808000",
    externalId: "68a9daac4dcd98",
    sku: "DARK-Olive-XL"
  },
  {
    key: "DARK-Olive-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Olive",
    colorHex: "#808000",
    externalId: "68a9daac4dcde6",
    sku: "DARK-Olive-2XL"
  },
  {
    key: "DARK-Red-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Red",
    colorHex: "#FF0000",
    externalId: "68a9daac4dc655",
    sku: "DARK-Red-S"
  },
  {
    key: "DARK-Red-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Red",
    colorHex: "#FF0000",
    externalId: "68a9daac4dc6a7",
    sku: "DARK-Red-M"
  },
  {
    key: "DARK-Red-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Red",
    colorHex: "#FF0000",
    externalId: "68a9daac4dc6f4",
    sku: "DARK-Red-L"
  },
  {
    key: "DARK-Red-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Red",
    colorHex: "#FF0000",
    externalId: "68a9daac4dc738",
    sku: "DARK-Red-XL"
  },
  {
    key: "DARK-Red-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Red",
    colorHex: "#FF0000",
    externalId: "68a9daac4dc784",
    sku: "DARK-Red-2XL"
  },
  {
    key: "DARK-Steel Blue-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "S",
    color: "Steel Blue",
    colorHex: "#4682B4",
    externalId: "68a9daac4dd2d1",
    sku: "DARK-Steel Blue-S"
  },
  {
    key: "DARK-Steel Blue-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "M",
    color: "Steel Blue",
    colorHex: "#4682B4",
    externalId: "68a9daac4dd321",
    sku: "DARK-Steel Blue-M"
  },
  {
    key: "DARK-Steel Blue-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "L",
    color: "Steel Blue",
    colorHex: "#4682B4",
    externalId: "68a9daac4dd376",
    sku: "DARK-Steel Blue-L"
  },
  {
    key: "DARK-Steel Blue-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "XL",
    color: "Steel Blue",
    colorHex: "#4682B4",
    externalId: "68a9daac4dd3c2",
    sku: "DARK-Steel Blue-XL"
  },
  {
    key: "DARK-Steel Blue-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "DARK",
    size: "2XL",
    color: "Steel Blue",
    colorHex: "#4682B4",
    externalId: "68a9daac4dd416",
    sku: "DARK-Steel Blue-2XL"
  },
  {
    key: "LIGHT-Ash-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287c311",
    sku: "LIGHT-Ash-S"
  },
  {
    key: "LIGHT-Ash-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287c367",
    sku: "LIGHT-Ash-M"
  },
  {
    key: "LIGHT-Ash-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287c3b2",
    sku: "LIGHT-Ash-L"
  },
  {
    key: "LIGHT-Ash-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287c409",
    sku: "LIGHT-Ash-XL"
  },
  {
    key: "LIGHT-Ash-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Ash",
    colorHex: "#F0F1EA",
    externalId: "68a9d8c287c443",
    sku: "LIGHT-Ash-2XL"
  },
  {
    key: "LIGHT-Athletic Heather-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287bea5",
    sku: "LIGHT-Athletic Heather-S"
  },
  {
    key: "LIGHT-Athletic Heather-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287bee3",
    sku: "LIGHT-Athletic Heather-M"
  },
  {
    key: "LIGHT-Athletic Heather-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287bf32",
    sku: "LIGHT-Athletic Heather-L"
  },
  {
    key: "LIGHT-Athletic Heather-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287bf85",
    sku: "LIGHT-Athletic Heather-XL"
  },
  {
    key: "LIGHT-Athletic Heather-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Athletic Heather",
    colorHex: "#CECECC",
    externalId: "68a9d8c287bfc6",
    sku: "LIGHT-Athletic Heather-2XL"
  },
  {
    key: "LIGHT-Heather Dust-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287c195",
    sku: "LIGHT-Heather Dust-S"
  },
  {
    key: "LIGHT-Heather Dust-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287c1e1",
    sku: "LIGHT-Heather Dust-M"
  },
  {
    key: "LIGHT-Heather Dust-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287c226",
    sku: "LIGHT-Heather Dust-L"
  },
  {
    key: "LIGHT-Heather Dust-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287c272",
    sku: "LIGHT-Heather Dust-XL"
  },
  {
    key: "LIGHT-Heather Dust-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Heather Dust",
    colorHex: "#E5D9C9",
    externalId: "68a9d8c287c2c5",
    sku: "LIGHT-Heather Dust-2XL"
  },
  {
    key: "LIGHT-Heather Prism Peach-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287bba4",
    sku: "LIGHT-Heather Prism Peach-S"
  },
  {
    key: "LIGHT-Heather Prism Peach-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287bbe7",
    sku: "LIGHT-Heather Prism Peach-M"
  },
  {
    key: "LIGHT-Heather Prism Peach-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287bc39",
    sku: "LIGHT-Heather Prism Peach-L"
  },
  {
    key: "LIGHT-Heather Prism Peach-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287bc83",
    sku: "LIGHT-Heather Prism Peach-XL"
  },
  {
    key: "LIGHT-Heather Prism Peach-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Heather Prism Peach",
    colorHex: "#F3C2B2",
    externalId: "68a9d8c287bcd5",
    sku: "LIGHT-Heather Prism Peach-2XL"
  },
  {
    key: "LIGHT-Mustard-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Mustard",
    colorHex: "#FFDB58",
    externalId: "68a9d8c287b9e7",
    sku: "LIGHT-Mustard-S"
  },
  {
    key: "LIGHT-Mustard-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Mustard",
    colorHex: "#FFDB58",
    externalId: "68a9d8c287ba54",
    sku: "LIGHT-Mustard-M"
  },
  {
    key: "LIGHT-Mustard-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Mustard",
    colorHex: "#FFDB58",
    externalId: "68a9d8c287bab6",
    sku: "LIGHT-Mustard-L"
  },
  {
    key: "LIGHT-Mustard-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Mustard",
    colorHex: "#FFDB58",
    externalId: "68a9d8c287bb05",
    sku: "LIGHT-Mustard-XL"
  },
  {
    key: "LIGHT-Mustard-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Mustard",
    colorHex: "#FFDB58",
    externalId: "68a9d8c287bb52",
    sku: "LIGHT-Mustard-2XL"
  },
  {
    key: "LIGHT-Pink-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Pink",
    colorHex: "#FFC0CB",
    externalId: "68a9d8c287bd24",
    sku: "LIGHT-Pink-S"
  },
  {
    key: "LIGHT-Pink-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Pink",
    colorHex: "#FFC0CB",
    externalId: "68a9d8c287bd79",
    sku: "LIGHT-Pink-M"
  },
  {
    key: "LIGHT-Pink-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Pink",
    colorHex: "#FFC0CB",
    externalId: "68a9d8c287bdc6",
    sku: "LIGHT-Pink-L"
  },
  {
    key: "LIGHT-Pink-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Pink",
    colorHex: "#FFC0CB",
    externalId: "68a9d8c287be03",
    sku: "LIGHT-Pink-XL"
  },
  {
    key: "LIGHT-Pink-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Pink",
    colorHex: "#FFC0CB",
    externalId: "68a9d8c287be52",
    sku: "LIGHT-Pink-2XL"
  },
  {
    key: "LIGHT-White-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287c495",
    sku: "LIGHT-White-S"
  },
  {
    key: "LIGHT-White-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287c4e9",
    sku: "LIGHT-White-M"
  },
  {
    key: "LIGHT-White-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287c535",
    sku: "LIGHT-White-L"
  },
  {
    key: "LIGHT-White-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287c584",
    sku: "LIGHT-White-XL"
  },
  {
    key: "LIGHT-White-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "White",
    colorHex: "#FFFFFF",
    externalId: "68a9d8c287c5d4",
    sku: "LIGHT-White-2XL"
  },
  {
    key: "LIGHT-Yellow-S",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "S",
    color: "Yellow",
    colorHex: "#FFFF00",
    externalId: "68a9d8c287c017",
    sku: "LIGHT-Yellow-S"
  },
  {
    key: "LIGHT-Yellow-M",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "M",
    color: "Yellow",
    colorHex: "#FFFF00",
    externalId: "68a9d8c287c063",
    sku: "LIGHT-Yellow-M"
  },
  {
    key: "LIGHT-Yellow-L",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "L",
    color: "Yellow",
    colorHex: "#FFFF00",
    externalId: "68a9d8c287c0b3",
    sku: "LIGHT-Yellow-L"
  },
  {
    key: "LIGHT-Yellow-XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "XL",
    color: "Yellow",
    colorHex: "#FFFF00",
    externalId: "68a9d8c287c0f2",
    sku: "LIGHT-Yellow-XL"
  },
  {
    key: "LIGHT-Yellow-2XL",
    catalogVariantId: 68,
    syncVariantId: 68,
    price: "24.99",
    design: "LIGHT",
    size: "2XL",
    color: "Yellow",
    colorHex: "#FFFF00",
    externalId: "68a9d8c287c149",
    sku: "LIGHT-Yellow-2XL"
  }
];

// Helper Functions
export function findTshirtVariant(design: 'DARK' | 'LIGHT', size: string, color: string): TshirtVariant | undefined {
  return TshirtVariants.find(variant => 
    variant.design === design && 
    variant.size === size && 
    variant.color === color
  );
}

export function findTshirtVariantByCatalogId(catalogId: number): TshirtVariant | undefined {
  return TshirtVariants.find(variant => variant.catalogVariantId === catalogId);
}

export function findTshirtVariantByExternalId(externalId: string): TshirtVariant | undefined {
  return TshirtVariants.find(variant => variant.externalId === externalId);
}

export function getTshirtVariantsByDesign(design: 'DARK' | 'LIGHT'): TshirtVariant[] {
  return TshirtVariants.filter(variant => variant.design === design);
}

export function getTshirtVariantsBySize(size: string): TshirtVariant[] {
  return TshirtVariants.filter(variant => variant.size === size);
}

export function getTshirtVariantsByColor(color: string): TshirtVariant[] {
  return TshirtVariants.filter(variant => variant.color === color);
}

// Get unique designs, sizes, and colors
export const tshirtDesigns = ['DARK', 'LIGHT'] as const;
export const tshirtSizes = ['S', 'M', 'L', 'XL', '2XL'] as const;

// Define the actual t-shirt colors with hex codes (arranged light to dark)
export const tshirtColors = [
  { name: 'White', hex: '#FFFFFF', border: true },
  { name: 'Ash', hex: '#F0F1EA' },
  { name: 'Athletic Heather', hex: '#CECECC' },
  { name: 'Heather Dust', hex: '#E5D9C9' },
  { name: 'Heather Prism Peach', hex: '#F3C2B2' },
  { name: 'Mustard', hex: '#FFDB58' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Mauve', hex: '#E0B0FF' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Heather Deep Teal', hex: '#2F4F4F' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Red', hex: '#FF0000' },
  { name: 'Autumn', hex: '#8B4513' },
  { name: 'Asphalt', hex: '#2F4F4F' },
  { name: 'Army', hex: '#4B5320' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Dark Grey Heather', hex: '#696969' },
  { name: 'Black Heather', hex: '#1C1C1C' },
  { name: 'Black', hex: '#000000' }
];

// Color design mapping for reference
export const colorDesignMapping: { [key: string]: 'DARK' | 'LIGHT' } = {
  // DARK design colors (white text)
  'Army': 'DARK',
  'Asphalt': 'DARK',
  'Autumn': 'DARK',
  'Black': 'DARK',
  'Black Heather': 'DARK',
  'Dark Grey Heather': 'DARK',
  'Heather Deep Teal': 'DARK',
  'Mauve': 'DARK',
  'Navy': 'DARK',
  'Olive': 'DARK',
  'Red': 'DARK',
  'Steel Blue': 'DARK',
  
  // LIGHT design colors (black text)
  'Ash': 'LIGHT',
  'Athletic Heather': 'LIGHT',
  'Heather Dust': 'LIGHT',
  'Heather Prism Peach': 'LIGHT',
  'Mustard': 'LIGHT',
  'Pink': 'LIGHT',
  'White': 'LIGHT',
  'Yellow': 'LIGHT'
};

// IMPORTANT: This ensures each color appears in exactly one design
// DARK design: 12 colors × 5 sizes = 60 variants
// LIGHT design: 8 colors × 5 sizes = 40 variants
// Total: 100 variants with NO overlapping colors
// Customer selects color + size, system auto-routes to correct Printful product
// DARK/LIGHT design is invisible to customers but ensures correct order routing
