// SAMPLE: This shows what your variant files will look like after running the Printful sync script
// This is NOT a real file - it's just for demonstration

// AUTO-GENERATED by scripts/printful-sync.ts — do not edit manually
// Generated on: 2025-01-27T10:30:00.000Z
// Total variants: 45

export type HoodieVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price?: string;
  name: string;
  externalId?: string;
  sku?: string;
};

export const HoodieVariants: HoodieVariant[] = [
  {
    key: "black-hoodie-s",
    catalogVariantId: 12345,  // Real Printful catalog variant ID
    syncVariantId: 67890,     // Your store's sync variant ID
    price: "39.99",
    name: "Black Hoodie - S",
    externalId: "hoodie-black-s",
    sku: "HOODIE-BLK-S",
  },
  {
    key: "black-hoodie-m",
    catalogVariantId: 12346,
    syncVariantId: 67891,
    price: "39.99",
    name: "Black Hoodie - M",
    externalId: "hoodie-black-m",
    sku: "HOODIE-BLK-M",
  },
  // ... more variants
];

// Helper function to find variant by key
export function findHoodieVariant(key: string): HoodieVariant | undefined {
  return HoodieVariants.find(v => v.key === key);
}

// Helper function to find variant by catalog variant ID
export function findHoodieVariantByCatalogId(catalogVariantId: number): HoodieVariant | undefined {
  return HoodieVariants.find(v => v.catalogVariantId === catalogVariantId);
}

// Migration helper: Convert old structure to new structure
export function migrateFromOldStructure(oldVariant: any): HoodieVariant | null {
  // This function helps migrate from your current structure
  // You can use this temporarily during the transition
  
  if (!oldVariant.printful_variant_id) {
    return null; // No Printful ID, can't migrate
  }
  
  // Try to find by the old printful_variant_id
  const migrated = findHoodieVariantByCatalogId(oldVariant.printful_variant_id);
  
  if (migrated) {
    return migrated;
  }
  
  // Fallback: create a basic structure (you'll need to update this)
  return {
    key: `${oldVariant.color.toLowerCase()}-hoodie-${oldVariant.size.toLowerCase()}`,
    catalogVariantId: oldVariant.printful_variant_id,
    syncVariantId: oldVariant.id,
    price: oldVariant.price,
    name: oldVariant.name,
    externalId: undefined,
    sku: undefined,
  };
}

// Usage examples:
/*
// OLD WAY (with mock IDs):
const oldVariant = hoodieVariants.find(v => v.color === "Black" && v.size === "S");
const lineItem = {
  variant_id: oldVariant.printful_variant_id, // ❌ Mock ID
  quantity: 1,
};

// NEW WAY (with real Printful IDs):
const newVariant = findHoodieVariant("black-hoodie-s");
const lineItem = {
  variant_id: newVariant!.catalogVariantId, // ✅ Real Printful catalog variant ID
  quantity: 1,
};

// Or find by catalog variant ID:
const variant = findHoodieVariantByCatalogId(12345);
if (variant) {
  console.log(`Found variant: ${variant.name} (${variant.key})`);
}

// Migration during transition:
const oldVariant = hoodieVariants.find(v => v.color === "Black" && v.size === "S");
const migrated = migrateFromOldStructure(oldVariant);
if (migrated) {
  // Use the new structure
  const lineItem = {
    variant_id: migrated.catalogVariantId,
    quantity: 1,
  };
}
*/
