// AUTO-GENERATED by scripts/printful-sync.ts — do not edit manually
// Generated on: 2025-08-26T22:53:27.844Z
// Total variants: 1

export type MugVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price?: string;
  name: string;
  externalId?: string;
  sku?: string;
};

export const MugVariants: MugVariant[] = [
  {
    key: "68a9f81d60c2b4",
    catalogVariantId: 1320,
    syncVariantId: 4938946337,
    price: "9.99",
    name: "Variant 4938946337",
    externalId: "68a9f81d60c2b4",
    sku: "68a9f81d60c2b4",
  },
];

// Helper function to find variant by key
export function findMugVariant(key: string): MugVariant | undefined {
  return MugVariants.find(v => v.key === key);
}

// Helper function to find variant by catalog variant ID
export function findMugVariantByCatalogId(catalogVariantId: number): MugVariant | undefined {
  return MugVariants.find(v => v.catalogVariantId === catalogVariantId);
}