// AUTO-GENERATED by scripts/printful-sync.ts — do not edit manually
// Generated on: 2025-08-26T22:53:27.844Z
// Total variants: 1

export type WaterbottleVariant = {
  key: string;
  catalogVariantId: number;
  syncVariantId: number;
  price?: string;
  name: string;
  externalId?: string;
  sku?: string;
};

export const WaterbottleVariants: WaterbottleVariant[] = [
  {
    key: "68a9f6414ae5b8",
    catalogVariantId: 20175,
    syncVariantId: 4938941055,
    price: "24.99",
    name: "Variant 4938941055",
    externalId: "68a9f6414ae5b8",
    sku: "68a9f6414ae5b8",
  },
];

// Helper function to find variant by key
export function findWaterbottleVariant(key: string): WaterbottleVariant | undefined {
  return WaterbottleVariants.find(v => v.key === key);
}

// Helper function to find variant by catalog variant ID
export function findWaterbottleVariantByCatalogId(catalogVariantId: number): WaterbottleVariant | undefined {
  return WaterbottleVariants.find(v => v.catalogVariantId === catalogVariantId);
}